apiVersion: apps/v1
kind: Deployment
metadata:
  name: vision-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: applicationtosellthingsapis
  template:
    metadata:
      labels:
        app: applicationtosellthingsapis
    spec:
      containers:
      - name: application-to-sell-things-apis
        image: applicationtosellthingsapis:dev
        imagePullPolicy: Never
        ports:
        - containerPort: 80